version: '3.9'

services:
  web:
    image: nginx:latest
    ports:
      - '9999:80'
    volumes:
      - ./src:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm

  php-fpm:
    #image: php:8-fpm
    build:
      context: .
      dockerfile: php/Dockerfile
    # volumes:
    #   - ./src:/var/www/html