version: "3.5"

services:
  api-01: &api
    # image: ana/minha-api-matadora:latest
    hostname: api01
    container_name: api-01
    environment:
      - APP_ENV=local
      - APP_DEBUG=false
      - APP_URL=http://localhost
      - APP_TIMEZONE=UTC
      - LOG_CHANNEL=stack
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres-db
      - DB_PORT=5432
      - DB_DATABASE=rinha_back_end
      - DB_USERNAME=postgres
      - DB_PASSWORD=rinha_back_end-PegaFogoCabare
      - QUEUE_CONNECTION=sync
    build:
      context: .
      dockerfile: php/Dockerfile
    depends_on:
        postgres:
          condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "100MB"
  
  api-02:
    <<: *api
    hostname: api-02
    container_name: api-02

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '9999:9999'
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-01
      - api-02
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "30MB"

  postgres:
    image: postgres:16-alpine
    hostname: postgres-db
    container_name: postgres
    command: -c 'config_file=/docker-entrypoint-initdb.d/postgresql.conf'
    environment:
      - POSTGRES_PASSWORD=rinha_back_end-PegaFogoCabare
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rinha_back_end
    volumes:
      - ./config/postgresql/script.sql:/docker-entrypoint-initdb.d/script.sql
      - ./config/postgresql/postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      timeout: 5s
      interval: 5s
      start_period: 10s
      retries: 20
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "220MB"

networks:
  default:
    driver: bridge
    name: rinha-2024q1